version: '3.7'

services:
  go_api_demo:
    container_name: go_api_demo
    image: go_api:dev
    build: .
    volumes:
      - ./config.yaml:/app/go_api_demo/config.yaml
    ports:
      - 8080:8080
      - 8082:8082
      - 50051:50051
